Fix a broken build
The tip of tree currently breaks at:
    ...
       Compiling sentry-types v0.31.8
       Compiling sentry-core v0.31.8
       Compiling sentry-contrib-breakpad v0.8.0
    error[E0599]: no function or associated item named `new_v4` found for
      struct `Uuid` in the current scope --> src/shared.rs:26:46
       |
    26 | .unwrap_or_else(types::Uuid::new_v4),
       |                              ^^^^^^
       |                              |
       | function or associated item not found in `Uuid`

This is due to the fact that a breaking change was introduced at
https://github.com/getsentry/sentry-rust/pull/614.